services:
  gai-rag-svr:
    image: kakkoii1337/gai-rag-svr:1.0.15
    environment:
      DEFAULT_GENERATOR: "rag-instructor-sentencepiece"
      LOG_LEVEL: "DEBUG"
      TZ: "Asia/Singapore"
      SWAGGER_URL: "/doc"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ~/.gai:/root/.gai
    ports:
      - "12036:12036"
      #- "5679:5679"
    networks:
      - default
    #restart: always

    #command: python -m debugpy --listen 0.0.0.0:5679 main.py
    #command: sleep infinity

